### ISSUE TITLE
scrollup/down mapping to <C-Up>/<C-Down> ?

### ISSUE THREAD

**Issue by mckelly2833** [bfrg/vim-qf-preview#10]
Hi,

Thank you for vim-qf-preview.
If I use:
```
let g:qfpreview = {
    \ 'top'   : "\<Home>",
    \ 'bottom': "\<End>",
    \ 'scrollup'  : "\<C-k>",
    \ 'scrolldown': "\<C-j>",
    \ 'halfpageup'  : "\<C-b>",
    \ 'halfpagedown': "\<C-f>",
    \ 'fullpageup'  : "\<PageUp>",
    \ 'fullpagedown': "\<PageDown>",
    \ 'next': "\<Down>",
    \ 'previous': "\<Up>",
    \ 'reset': "r",
    \ 'close': "q",
    \ 'number': "1",
    \ 'height': "15",
    \ 'offset': "7",
    \ 'sign': {'linehl': 'CursorLine'},
    \ }
```
Everything works fine.  But if I change the \<C-k\>/\<C-j\> to \<C-Up\>/\<C-Down\>, as in:
```
    \ 'scrollup'  : "\<C-Up>",
    \ 'scrolldown': "\<C-Down>",
```
Then these do not work anymore.  I do use \<C-Up\>/\<C-Down\> successfully for other things in vim (not in popup)
Do you know if it is possible to make this work ?

thx,
-m

**Comment by bfrg** [comment]
It works fine on my system. But for some reason it doesn't work when I run vim inside tmux.

Note: The entries `number`, `height` and `offset` expect numbers and not strings.

**Comment by mckelly2833** [comment]
@bfrg ok, thanks - yes I am using tmux also.  I will investigate that.

**Comment by bfrg** [comment]
Can you try it outside tmux?

**Comment by mckelly2833** [comment]
It does not work outside of tmux for me.

**Comment by bfrg** [comment]
Can you try this minimal test script? Run `vim --clean test.vim -S test.vim`, with
```vim
" test.vim
function s:popup_filter(winid, key) abort
    if a:key ==# "\<C-Up>"
        call win_execute(a:winid, "normal! \<c-y>")
    elseif a:key ==# "\<C-Down>"
        call win_execute(a:winid, "normal! \<c-e>")
    elseif a:key ==# 'q'
        call popup_close(a:winid)
    endif
    return v:true
endfunction

call range(1, 20)
        \ ->map({_, i -> string(i)})
        \ ->popup_create({
        \   'close': 'button',
        \   'minwidth': 50,
        \   'maxwidth': 50,
        \   'minheight': 5,
        \   'maxheight': 5,
        \   'border': [],
        \   'mapping': v:false,
        \   'filter': funcref('s:popup_filter'),
        \   'filtermode': 'n'
        \ })
```

And try scrolling with `CTRL-Up` and `CTRL-Down`, close with `q` or `CTRL-C`.

**Comment by mckelly2833** [comment]
ok, interesting.
1). rxvt - works outside of tmux, fails inside of tmux
2). kitty - works outside of tmux, fails inside of tmux
3). alacritty - fails outside of tmux, fails inside of tmux   <-- my default terminal

**Comment by mckelly2833** [comment]
I will research this, thx.  We can close the issue.  I appreciate any additional help.
What is odd to me is \<C-Up\> and \<C-Down\> work properly for other non-menu mappings both inside and outside of tmux for my terminal.

**Comment by bfrg** [comment]
This seems to be a Vim bug. I don't think it has anything to do with popup windows.

The following minimal mappings demonstrate it:
```vim
nnoremap <C-Up> :echomsg "CTRL-Up"<CR>
nnoremap <C-Down> :echomsg "CTRL-Down"<CR>
```

Can you open a new issue for this in the Vim repo?

**Comment by mckelly2833** [comment]
ok

**Comment by mckelly2833** [comment]
@bfrg are you saying these mappings do not work ?
I added those to my .vimrc and they do echo for me both in and out of tmux in my default terminal.

**Comment by mckelly2833** [comment]
I can work-around it by changing my tmux to send \<C-j\> for \<C-Down\> when inside vim, but that is a bit of a hammer.

**Comment by mckelly2833** [comment]
ok, I think the point is the echo mappings work ok but the menu does not.
I will submit that bug to vim today.
thx again

**Comment by mckelly2833** [comment]
@bfrg hi
Not exactly sure why yet, but if I add these to my .vimrc -
```
  exec "set <xHome>=\e[1;*H"
  exec "set <xEnd>=\e[1;*F"
```
Then \<C-Up\> and \<C-Down\> now work ok in the qf-preview popup.

**Comment by bfrg** [comment]
Thanks for the info. I think we should still open an issue on this in the vim repo. Here's what I'm observing: 

The two `echo` mappings:
- `xfce4-terminal`: work outside tmux, fail inside tmux
- `xterm`: fail outside tmux, fail inside tmux

Popup scrolling with `<C-Up>` and `<C-Down>`:
- `xfce4-terminal`: work outside tmux, fail inside tmux
- `xterm`: work outside tmux, fail inside tmux

 And I'm observing similar behavior for `<C-Left>` and `<C-Right>`.

**Comment by mckelly2833** [comment]
ok.  Do these work ok when you add:
```
  exec "set <xUp>=\e[1;*A"
  exec "set <xDown>=\e[1;*B"
  exec "set <xRight>=\e[1;*C"
  exec "set <xLeft>=\e[1;*D"
```
and what is your terminal set to inside tmux ?  (I used screen-256color, but just switched to tmux-256color)

**Comment by mckelly2833** [comment]
The vim --clean test.vim -S test.vim test (without any addl set \<xUp\>) works ok in my xterm outside of tmux, \<C-Up\> works in the popup menu and echoes.
