### ISSUE TITLE
close actions can't be mapped

### ISSUE THREAD

**Issue by yan42685** [bfrg/vim-qf-preview#4]
![image](https://user-images.githubusercontent.com/41834091/75702644-ce397580-5cf0-11ea-9deb-75304896e60e.png)
All but close actions can be mapped to certain keys.
I can bind <c-d> to page down but failed in binding q to close the preview window.
Strangely `close` is highlighted in my color scheme (one-dark). Maybe it is recognized as a semantic keyword?

**Comment by bfrg** [comment]
Which Vim version do you use?

Do you have `q` already mapped in the `quickfix` buffer?
With the cursor in the quickfix window, can you run `:verbose map q`?

Regarding the highlighting: can you run `vim --clean` and see if the highlighting still occurs when you open the above file? It's either your colorscheme, or you have outdated `runtime` files that don't support the `${}` syntax. It could also be another plugin. It looks like you're highlighting the curly braces somehow, is that done by another plugin?

**Comment by bfrg** [comment]
You can check the syntax group of `close` with the following:
```vim
" Print stack of syntax highlighting groups for word under the cursor
function! s:synstack()
    echo join(map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")'), ' -> ')
endfunction

nnoremap <F5> :<C-u>call <SID>synstack()<CR>
```
Put your cursor on `close` and press `<F5>`.

**Comment by yan42685** [comment]
My Vim version is 8.2 and I have installed  Plug 'luochen1990/rainbow' to highlight curly braces.
After running the function you provide, it reveals:
```
vimRainbow_lv0_r2 -> vimIsCommand -> vimCommand 
```
Thanks for your detailed reply.

**Comment by yan42685** [comment]
And I have solved the problem because I make a silly mistake.
I mixed the quickfix window provided by `:CocList --normal quickfix` and by native Vim.
I am sorry for wasting your time. 😭
