### ISSUE TITLE
added mappings ?

### ISSUE THREAD

**Issue by mckellyln** [bfrg/vim-qf-preview#5]
Hi,
Thanks for an awesome plugin.
I was wondering about adding:
1). additional mappings for close (ie q, \<Esc\>, \<C-c\>, etc.)
2). an auto popup mode where scrolling in qf auto pops the preview
Would you consider such features ?  If so I will look into it.
thx,
-m

**Comment by bfrg** [comment]
>  1). additional mappings for close (ie q, , , etc.)

You can change the default key for closing the popup window, see the [configuration](https://github.com/bfrg/vim-qf-preview#bqfpreview-and-gqfpreview) section, or `:help qfpreview-config`. For example:
```vim
let g:qfpreview = {'close': 'q'}
```
Or do you want both `x` and `q` for closing the popup window? What exactly do you mean with the _etc._?

>  2). an auto popup mode where scrolling in qf auto pops the preview

I already thought about something similar. I started experimenting with two new popup mappings `CTRL-N` and `CTRL-P` that jump to the next and previous quickfix item, respectively. I need to test it a bit before pushing it upstream. Adding an optional auto popup mode is also possible. Maybe using the `CursorHold` event?

**Comment by mckellyln** [comment]
Hi, Yes I meant > 1 close mapping, ie  q, <Esc>, <C-c>, x to all be close keys, if possible.
I have <C-n> and <C-p> now in qf that just move down/up - perhaps I could remap those to move and pop ?  I'll experiment.  thx.

**Comment by bfrg** [comment]
I have added a new option `auto` will automatically open the preview popup when the `CursorHold` event is triggered. You can specify the time when it pops up with `'updatetime'`. You can try it out, see #6.

Unfortunately `'updatetime'` is a global option. I tried to use the `CursorMoved` event and `timers` but there seems to be a Vim bug that messes everything up when a swap file for a buffer already exists. See https://github.com/vim/vim/issues/6541.

Regarding additional mappings for closing the popup window, `CTRL-C` always closed the popup window (this can't be changed). I changed the default key to `q` which is probably more intuitive than `x`. But I don't think I want to add an option for specifying a list of keys that do the same thing.

**Comment by mckellyln** [comment]
ok, thank you.

**Comment by bfrg** [comment]
I have added two new options, `next` and `previous` that allow you to jump to the next and previous quickfix entry while the popup window is open. This is like closing the popup window, moving the cursor to the next valid quickfix entry and then opening the popup again. You can bind it to `CTRL-N` and `CTRL-P`, or even `n` and `p` directly.

Personally, I prefer `next` and `previous` over the `auto` option in #6.

**Comment by mckellyln** [comment]
ok, awesome.
Without trying it yet, can I have a multi-character mapping in the qflist ?

**Comment by mckellyln** [comment]
Thank you again for your work and this great plugin.

**Comment by mckellyln** [comment]
I think I could map next and previous to <down> and <up> and it would be exactly what I was originally asking about :-)

**Comment by bfrg** [comment]
No, multi-character mappings are not possible, see `:h popup-filter`. There would be a way around this but I don't think I want to implement it.

While the popup window is visible the popup keys override the default quickfix mappings anyway. So it shouldn't be hard to find a key for every scrolling or navigation option. Besides, I made it possible to set the entries to `""` to disable the option in case someone doesn't need them. For example, if you don't need `halfpageup` and `halfpagedown` just leave them out, or assign them to an empty string.

**Comment by mckelly2833** [comment]
@bfrg hi
Just to follow on here, I just added additional dict items: close2, scrollup2, scrolldown2 and mappings for those to get the duplicate mappings I wanted.
thx again for this great plugin,
-m
